CPP = g++
CFLAGS = -Wall -std=c++11 -O3

all:
	${CPP} ${CFLAGS} -o solution solution.cpp
eratos:
	${CPP} ${CFLAGS} -o eratosthenes eratosthenes.cpp
debug:
	${CPP} ${CFLAGS} -g -Og -o solution solution.cpp

clean:
	rm solution eratosthenes
